server:
  port: 9099
  servlet:
    context-path: /



spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/expriment?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    #严格执行H5标准
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html





  #content-type: text/html
resources:
  chain:
    strategy:
      content:
        enabled: true
        paths: /**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE

pagehelper:
  support-methods-arguments: true
  helper-dialect: true
  reasonable: true
  params: countSql
  page-size-zero: true



